[project]
name = "ml-models"
version = "0.0.1"
description = "Simple ML models (linear regression, logistic regression, classification)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
]
